os: windows
language: shell

env:
  - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"
  
install:
  - choco install sysinternals
  - psexec -s powershell.exe -command 'Add-WindowsCapability –Online -Name NetFx3~~~~'
  - choco install python2 python3 7zip
  
before_script:
  - export PATH=$MSBUILD_PATH:$PATH
  
script:
  - msbuild.exe HastyArp/HastyArp.sln /m -p:Configuration=Release
