os: windows
language: shell

env:
  - MSBUILD_PATH="/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"

install:
  - choco install python2 python3 7zip.install
  - PowerShell -Command 'dism.exe /online /enable-feature /featurename:NetFX3 /All /Source:c:\temp\sxs /LimitAccess'
  
before_script:
  - export PATH=$MSBUILD_PATH:$PATH
  
script:
  - msbuild.exe HastyArp/HastyArp.sln
